- README.md
This is a test pull request to pull my change in the README to the develop branch
> Added name to README for testing purposes

- README.md
> Readme- Test Changes

- UMLEditor/UMLEditor.NetCore/Program.cs
- UMLEditor/UMLEditor/Classes/Attribute.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/UMLEditor.csproj
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Created classes for diagram, class, attribute, relationship
> Added Data Structures

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Tests/DiagramTest.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Added functionality for List Classes Button, also created DiagramTest class to create a diagram for testing
> Add List Classes, Add DiagramTest class

- UMLEditor/UMLEditor/Classes/Attribute.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/JSONDiagramFile.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Interfaces/IDiagramFile.cs
- UMLEditor/UMLEditor/UMLEditor.csproj
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
You can now save and load diagrams to JSON files
> Implemented Saving / Loading

- UMLEditor/.idea/.idea.UMLEditor/.idea/.gitignore
- UMLEditor/.idea/.idea.UMLEditor/.idea/avalonia.xml
- UMLEditor/.idea/.idea.UMLEditor/.idea/encodings.xml
- UMLEditor/.idea/.idea.UMLEditor/.idea/indexLayout.xml
- UMLEditor/.idea/.idea.UMLEditor/.idea/vcs.xml
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Added list classes functionality to button to display all classes
> Added List Classes

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
List relationships button is now working
> Added List Relationships

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
List Attributes function is now operational
> Added List Attributes

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Created Add Class button and implemented AddClass function in diagram
> Add Class implemented

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Implemented rename class and slightly refactored the class name validation code to a seperate function that both rename class and name class call
> Implemented rename class

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Implemented add attribute plus did some code refactoring to make add attribute work better with currently written code
> Implemented Add Attribute

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
This pull request has issues that are preventing the project from compiling.
See issue #51 for more details
> Revert "Feature delete relationship"

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Fixed the fields of Source Class and Destination Class
RelationshipExists was for some reason not added. Added to file diagram
RealtionshipNonexistant was not added for some reason. Added to file CustomExceptions.
If any issues found please let me know.
> Feature delete relationship

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Added ClassInUseException to handle DeleteClass functionality when the requested class is in use by a relationship and cannot be deleted.
> Added ClassInUseException

- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
I added some constraints to rename attribute and delete relationship.
> Feature attribute relationship fixes

- UMLEditor/UMLEditor/Views/MainWindow.axaml
Refined some UI elements, made the button widths uniform and axed the extra button.
> UI refinement

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Changed name validation such that is checked by the object instead of the view.  Also added comments to functions that needed comments.
> Refactored name validation

- UMLEditor/UMLEditor.NetCore/Program.cs
- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/JSONDiagramFile.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Interfaces/IDiagramFile.cs
- UMLEditor/UMLEditor/Testing/AttributeTester.cs
- UMLEditor/UMLEditor/Testing/ClassTester.cs
- UMLEditor/UMLEditor/Testing/RelationshipTester.cs
- UMLEditor/UMLEditor/Testing/TestingSled.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Applied code refactoring mentioned in issue #57 and bugfixes for issue #66 and #54
> Project refactoring

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UnitTests/RelationshipUnitTests.cs
Added types to relationship class and exception throwing for invalid values. Updated testing code.
> Added types to relationships

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/JSONDiagramFile.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/NameTypeObject.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Interfaces/IDiagramFile.cs
- UMLEditor/UMLEditor/ViewModels/MainViewModel.cs
- UMLEditor/UMLEditor/ViewModels/ViewModelBase.cs
- UMLEditor/UMLEditor/Views/MainView.axaml.cs
- UnitTests/AttributeUnitTests.cs
- UnitTests/ClassUnitTests.cs
Added add/change/remove functions for Parameters.
Rewrote unit tests to handle Method types.
Added unit tests for Parameters.
> Feature add parameter

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UnitTests/RelationshipUnitTests.cs
Reverted change to throwing exception for an invalid method name.
Added function to change type of a Relationship, as well as unit tests for it.
> Added ChangeType to Relationship Class

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/NameTypeObject.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UnitTests/ClassUnitTests.cs
Changed all List fields in Diagram.cs, Class.cs, and Method.cs to private and created publically accessed Lists that are copies of the private members to ensure data integrity.
> Field accessor fixes

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/NameTypeObject.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Utility/Utilities.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Added utility class that can clone containers whose elements are clonable. Refactored classes to implement clonable (so containers of them can be cloned). Updated the public accessors and class ctors to use the utility container clone function. Did some light refactoring to shut up compiler warnings.
> Refactored field accessors

- UMLEditor/UMLEditor.NetCore/Program.cs
- UMLEditor/UMLEditor/Views/CommandLine.cs
Fixed arguments for loading files as well as help
> fixed #109

- README.md
added testing instructions and removed warning for cli since this has now been implemented
> fixed #105 Changed README

- .idea/.idea.UMLEditor/.idea/avalonia.xml
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/UMLEditor.csproj
- UMLEditor/UMLEditor/Views/AddFieldPanel.axaml
- UMLEditor/UMLEditor/Views/AddFieldPanel.axaml.cs
- UMLEditor/UMLEditor/Views/AddMethodPanel.axaml
- UMLEditor/UMLEditor/Views/AddMethodPanel.axaml.cs
- UMLEditor/UMLEditor/Views/AddRelationshipPanel.axaml
- UMLEditor/UMLEditor/Views/AddRelationshipPanel.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UMLEditor/UMLEditor/Views/RenameClassPanel.axaml
- UMLEditor/UMLEditor/Views/RenameClassPanel.axaml.cs
- UMLEditor/UMLEditor/Views/RenameFieldPanel.axaml
- UMLEditor/UMLEditor/Views/RenameFieldPanel.axaml.cs
- UMLEditor/UMLEditor/Views/RenameMethodPanel.axaml
- UMLEditor/UMLEditor/Views/RenameMethodPanel.axaml.cs
Finished up all functionality for menu bar items that we would like currently.  Some will be deleted when the visual representation of classes becomes fully realized.
> Feature menu bar functionality

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Fixed some bugs relating to the order in which we handled errors ie we were checking if a class existed before we checked if the input submitted was empty
> Wording & Error Handling Fixes

- UMLEditor/UMLEditor/Views/AlertPanel.axaml.cs
- UMLEditor/UMLEditor/Views/ModalDialog.axaml.cs
Went through and documented the code that was severely needing some explanation
> Documentation Pass For 'experimental-modal-dialogs'

- .idea/.idea.UMLEditor/.idea/avalonia.xml
- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Views/AddFieldPanel.axaml
- UMLEditor/UMLEditor/Views/ClassBox.axaml
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/FieldContainer.axaml
- UMLEditor/UMLEditor/Views/FieldContainer.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UMLEditor/UMLEditor/Views/MethodContainer.axaml
- UMLEditor/UMLEditor/Views/MethodContainer.axaml.cs
- UMLEditor/UMLEditor/Views/ModalDialog.axaml.cs
- UMLEditor/UMLEditor/Views/ParameterContainer.cs
Basic framework for operating classes in the GUI
Here is what should work:
- Adding classes
- Deleting classes
- Renaming classes
- Adding/ removing class fields
- Deleting parameters from a method (adding methods is not ready yet, will need to load a diagram that has a method to test this)
- Class boxes are movable
> Feature graphical classes

- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
Also added any additional methods needed to facilitate these two things (in Class and Method)
> Add field/ parameter rename methods in Diagram

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/NameTypeObject.cs
- UMLEditor/UMLEditor/Views/AddClassPanel.axaml
- UMLEditor/UMLEditor/Views/AddFieldPanel.axaml.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/FieldContainer.axaml.cs
- UMLEditor/UMLEditor/Views/MethodContainer.axaml.cs
- UMLEditor/UMLEditor/Views/ParameterContainer.cs
You can now edit parameters and fields in the GUI (note: You will need to load a diagram with a method to test this)
> GUI- Add edit field/ parameter functionality

- .idea/.idea.UMLEditor/.idea/avalonia.xml
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
- UMLEditor/UMLEditor/Views/ChangeRelationshipPanel.axaml
- UMLEditor/UMLEditor/Views/ChangeRelationshipPanel.axaml.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/CommandLine.cs
- UMLEditor/UMLEditor/Views/DeleteRelationshipPanel.axaml
- UMLEditor/UMLEditor/Views/DeleteRelationshipPanel.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Integrated with the visual representation of classes, along with misc fixes.
> Integrated relationship lines

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Refactored the various guts of our project to use the cleaner string interpolation method of inserting variables directly into strings, this also reduced a few of the warnings we have been getting.  This is a few commits behind develop so some things might need to be sorted out.
> String Interpolation Refactor

- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Opens default browser window to display main GitHub page with readme instructions.
> Added gui help menu functionality

- UMLEditor/UMLEditor/Classes/Diagram.cs
Added a method within diagram to check if a method exists or not to reduce repetitive nature of our code
> Refactor Has Class

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/Relationship.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/CommandLine.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
> Added Single Quotes to Distinguish User Input

- UMLEditor/UMLEditor/Utility/Utilities.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
Class box dragging is now based on the clicked location, negative coordinates are now disallowed, the class box can now show more fields and methods, the cursor changes when you hover over the class title bar.
> Refine Class Box movement

- UMLEditor/UMLEditor/Classes/BoxLocation.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
The location of classes is now saved in the file and can be restored when loaded
> Add location recall on gui

- UMLEditor/UMLEditor/Views/ClassBox.axaml
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/FieldContainer.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UMLEditor/UMLEditor/Views/MethodContainer.axaml
- UMLEditor/UMLEditor/Views/MethodContainer.axaml.cs
- UMLEditor/UMLEditor/Views/ParameterContainer.cs
Class buttons are hidden in view mode, shown in edit mode
> Added Edit/ View modes

- UMLEditor/UMLEditor/Classes/Diagram.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/CommandLine.cs
> Refactor sprint2 cli command name command messages

- UMLEditor/UMLEditor/Classes/TimeMachine.cs
- UnitTests/TimeMachineUnitTests.cs
TimeMachine is a doubly linked list to track the history of diagram states that enables traversing forwards and backwards.
> Added TimeMachine class

- .github/workflows/codecov.yml
- .github/workflows/main.yml
Get rid of branch that was accidently created
> Mayoung00 patch 1

- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Undo/ redo works, except for changes made after an undo (TM bug)
** There seems to be a bug with the TimeMachine when you make a new change after undoing a previous change.
> GUI- implement undo/ redo

- UMLEditor/UMLEditor/Classes/AttributeObject.cs
- UMLEditor/UMLEditor/Classes/Class.cs
- UMLEditor/UMLEditor/Classes/Method.cs
- UMLEditor/UMLEditor/Classes/NameTypeObject.cs
- UnitTests/AttributeUnitTests.cs
- UnitTests/ClassUnitTests.cs
- UnitTests/RelationshipUnitTests.cs
Got our overall model code coverage up to a nice amount.
> Refactor testing sprint3

- UMLEditor/UMLEditor/App.axaml
- UMLEditor/UMLEditor/App.axaml.cs
- UMLEditor/UMLEditor/ViewModels/MainViewModel.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- Fixed the native menu on macOS
- Moved exit to be under file
- Added keyboard shortcuts for most commands
> Refactor menubar improvements

- UMLEditor/UMLEditor/Views/MainWindow.axaml
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
You can now export the diagram view to a .png file!
> Added image exporting

- UMLEditor/UMLEditor/Views/EdgeEnum.cs
- UMLEditor/UMLEditor/Views/RelationshipLine.cs
Used the recent line refactors to fix the render bug for lines clipping through boxes & symbols.
> Feature lines render fixes

- UMLEditor/UMLEditor/Views/AStarSharp.cs
- UMLEditor/UMLEditor/Views/ClassBox.axaml.cs
- UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
- UMLEditor/UMLEditor/Views/RelationshipLine.cs
Fixed major bugs with performance in A*
> Magic lines optimize
